#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "compiler: @CMAKE_C_COMPILER@ @CMAKE_C_FLAGS@"
  #define PLATFORM "platform: @CMAKE_SYSTEM_NAME@"
  #define DATE "built on: @BUILDINF_DATE@"
#endif

